In [6]:
import pandas as pd
import numpy as np
import os, random, math, glob
from IPython.display import Image as IM
from IPython.display import clear_output
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression
from math import sqrt
from sklearn.model_selection import KFold
from sklearn.cluster import KMeans
%matplotlib inline
plt.rcParams['figure.figsize'] = [16, 10]

plt.rcParams['figure.figsize'] = [16, 10]

In [25]:
df = pd.read_csv('Train.csv')
df_test = pd.read_csv('Test.csv')


In [26]:
X = df[['lat', 'lon']]

#kmeans = KMeans(n_clusters = 7, random_state = 0). fit(X)

In [11]:
kmeans.labels_

array([2, 2, 2, ..., 2, 2, 2], dtype=int32)

In [13]:
kmeans.cluster_centers_

array([[-23.90221349,  30.02965606],
       [-27.53304248,  31.18107511],
       [-27.52506674,  24.74725302],
       [-25.94480163,  28.13588726],
       [-29.88192624,  20.01885275],
       [-29.68952452,  30.63172938],
       [-28.27542057,  27.20244197]])

In [19]:
X["labels"]= kmeans.labels_
X.plot.scatter(x = "lat", y="lon", c = labels, s=50, cmap="virdis")

/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


NameError: name 'labels' is not defined

In [27]:
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris
pca = PCA(n_components=2).fit(X)
pca_2d = pca.transform(X)

In [30]:
import pylab as pl
for i in range(0, pca_2d.shape[0]):
    if X[i] == 0:
        c1 = pl.scatter(pca_2d[i,0],pca_2d[i,1],c='r',
        marker='+')
    elif X[i] == 1:
        c2 = pl.scatter(pca_2d[i,0],pca_2d[i,1],c='g',
        marker='o')
    elif X[i] == 2:
        c3 = pl.scatter(pca_2d[i,0],pca_2d[i,1],c='b',
        marker='*')
        pl.legend([c1, c2, c3], ['Setosa', 'Versicolor',
        'Virginica'])
        pl.title('Iris dataset with 3 clusters and known')
        pl.show()

KeyError: 0

In [15]:
df = pd.DataFrame({
    'x': [12, 20, 28, 18, 29, 33, 24, 45, 45, 52, 51, 52, 55, 53, 55, 61, 64, 69, 72],
    'y': [39, 36, 30, 52, 54, 46, 55, 59, 63, 70, 66, 63, 58, 23, 14, 8, 19, 7, 24]
})



k = 4
centroids = {
    i+1: [np.random.randint(0,80), np.random.randint(0.80)]
    for i in range(k)
}

fig = plt.figure(figsize = (5,5))

plt.scatter(df['x'], df['y'], color='k')
colmap = {1: 'r', 2: 'g', 3: 'b'}
for i in centroids.keys():
    plt.scatter(*centroids[i], color=colmap[i])
plt.xlim(0, 80)
plt.ylim(0, 80)
plt.show()


ValueError: Range cannot be empty (low >= high) unless no samples are taken

In [12]:
df = pd.DataFrame({
    'x': [12, 20, 28, 18, 29, 33, 24, 45, 45, 52, 51, 52, 55, 53, 55, 61, 64, 69, 72],
    'y': [39, 36, 30, 52, 54, 46, 55, 59, 63, 70, 66, 63, 58, 23, 14, 8, 19, 7, 24]
})


np.random.seed(200)
k = 3
# centroids[i] = [x, y]
centroids = {
    i+1: [np.random.randint(0, 80), np.random.randint(0, 80)]
    for i in range(k)
}
    
fig = plt.figure(figsize=(5, 5))
plt.scatter(df['x'], df['y'], color='k')
colmap = {1: 'r', 2: 'g', 3: 'b'}
for i in centroids.keys():
    plt.scatter(*centroids[i], color=colmap[i])
plt.xlim(0, 80)
plt.ylim(0, 80)
plt.show()

array([4, 0], dtype=int32)